services:
  - type: web
    name: plot-twist
    runtime: node
    buildCommand: |
      npm install && \
      cd plot-twist && npm install && npm run build && cd .. && \
      cd backend && npm install && cd ..
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: "5000"
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        scope: build,run
